data:
  crop_size:
  - 120
  - 120
  delimiter: _
  maxvalues:
  - 1024
  prob_train: 0.8
  root_folder: mscanData/pngs_anotados/Smart4Olives/
  terminaciones:
  - _r.png
  - _g.png
  - _b.png
  - _a.png
  - _nir.png
  - _nir1.png
  - _nir2.png
  - _nir4.png
  train:
  - - train_list.txt
    - season_2022/manzanilla/Season_oct_2022_set01_rev1/jsons
    - season_2022/manzanilla/Season_oct_2022_set01_rev1/images
  - - train_list.txt
    - season_2023/ANOTADAS_IRENE/all/manzanilla/jsons
    - season_2023/ANOTADAS_IRENE/all/manzanilla/images
  val:
  - - val_list.txt
    - season_2022/manzanilla/Season_oct_2022_set01_rev1/jsons
    - season_2022/manzanilla/Season_oct_2022_set01_rev1/images
  - - val_list.txt
    - season_2023/ANOTADAS_IRENE/all/manzanilla/jsons
    - season_2023/ANOTADAS_IRENE/all/manzanilla/images
model:
  defect_types:
  - agostado
  - envero
  - escudete
  - molestadograve
  - molestadoleve
  - negra_morada
  multilabel: true
  num_channels_input: 8
  resnet_version: 50
train:
  affine:
    scale:
    - 0.7
    - 1.1
    shear: 15
    translate:
    - 0.15
    - 0.15
  augmentation:
    brightness: 0.1
    contrast: 0.1
    hue: 0.1
    saturation: 0.1
  batch_size: 60
  epochs: 50
  in_memory: true
  initial_model: null
  label_smoothing: 0.1
  learning_rate: 0.01
  mixup_alpha: 0.2
  optimizer: adam
  output:
    mdel_file: ' Olives_Multilabel_2022_2023_morada_negra.ckpt'
    path: out_models
  p_dropout: 0.5
  random_rotation: 30
  unfreeze_epoch: 7
  warmup: 3
  weights_decay: 0.001
